export const ChatIntents = {
    // About
    ABOUT_ME: 'QUERY_ABOUT_ME',
    BACKGROUND: 'QUERY_BACKGROUND',
    INTERESTS: 'QUERY_INTERESTS',
    VISION: 'QUERY_VISION',

    // Projects
    PROJECTS_WEB: 'QUERY_PROJECTS_WEB',
    PROJECTS_AI: 'QUERY_PROJECTS_AI',
    PROJECTS_ALL: 'QUERY_PROJECTS_ALL', // Dynamic fallback

    // Skills
    SKILLS_FRONTEND: 'QUERY_SKILLS_FRONTEND',
    SKILLS_BACKEND: 'QUERY_SKILLS_BACKEND',
    SKILLS_DESIGN: 'QUERY_SKILLS_DESIGN',
    SKILLS_OTHER: 'QUERY_SKILLS_OTHER',
    SKILLS_ALL: 'QUERY_SKILLS_ALL',

    // Experience
    WORK_HISTORY: 'QUERY_WORK_HISTORY',
    EDUCATION: 'QUERY_EDUCATION',
} as const;

export type ChatIntentType = typeof ChatIntents[keyof typeof ChatIntents];
